### ISSUE TITLE
Documented Python Version is Confusing

### ISSUE THREAD

**Issue by evannadeau** [aws/git-remote-codecommit#25]
The documentation states this

>The git-remote-codecommit package works on Python versions:
>
>3.6.x and greater
>3.7.x and greater

Does this in fact mean that it is not intended to work on 3.8, 3.9 and the upcoming 3.10? I was trying to get it working 3.9.x, and failing.  If this is the case, I suggest it says;

>3.6.x
>3.7.x

**Comment by ZhwuAMZN** [comment]
Hi,

Sorry for the confused documentation.

I've updated the README to explicitly say that python 3.8/3.9 are supported. I've tested the tool with different python versions on both Linux/Windows, and verified all of them working.

If you find the tool not working only on a specific python version, please feel free to share the error trace so that we can take a deeper look.

Thanks!
