### ISSUE TITLE
remote-codecommit is not a git command.

### ISSUE THREAD

**Issue by priyankaVice** [aws/git-remote-codecommit#4]
While running the git pull or git clone, it says remote-codecommit is not a git command. help would be appreciable.

**Comment by tfindlay-au** [comment]
I have this same issue, how did you resolve it ?

**Comment by tfindlay-au** [comment]
I had the same issue. Was able to resolve it by installed awscli package and checking the Python scripts folder was in my path statement.

```
> pip install --user awscli
> SET PATH=C:\Users\<username>\AppData\Roaming\Python\Python37\Scripts;%PATH%
> aws codecommit help
```

**Comment by ErickMwazonga** [comment]
> While running the git pull or git clone, it says remote-codecommit is not a git command. help would be appreciable.

I am having this issue on Windows, I have tried the suggested solution above but still no luck.

**Comment by etelenchenko** [comment]
Have you found a solution to this issue?

**Comment by evannadeau** [comment]
@ErickMwazonga @etelenchenko Is your Python version 3.8.x or 3.9.x ??  This was my issue.  Although not getting any errors during the pip install, it does not put the scripts into the scripts folder.  Install 3.7.x and have those paths at the top of your path environment order and rerun the pip install command, and it should install the scripts into the Python37\Scripts folder.

**Comment by atul-verifiably** [comment]
First, it is worth understanding how custom git commands work since support for codecommit:// repositories is added by using a custom command.

Anyone can add any custom commands to git. For example if you wanted to add: git new-command, you would need to create an executable called git-new-command and it needs to be on the PATH.

So when you get the error remote-codecommit is not a git command, that means that the executable 'git-remote-codecommit' is not on the PATH.

A simple way to test this is to run: git-remote-codecommit, it probably doesn't work if you were getting that error.

For me personally I ran into this error by making the mistake of running:
`pip install git-remote-codecommit` -> installs to ~/.local/bin (not on my PATH)
instead of:
`sudo pip install git-remote-codecommit` -> install to /usr/local/bin (already on my PATH)

Your personal error may not be exactly the same but is very likely due to the command not being on the PATH.

**Comment by LokoMoloko98** [comment]
This worked, Thanks a lot.
